### ISSUE TITLE
CSS file: px-timeline-styles.html has wrong path for font-awesome icons.

### ISSUE THREAD

**Issue by anundinesh** [predixdesignsystem/px-timeline#1]
Below error we are getting because of font awesome path was wrong in css/px-timeline-styles.html. 
![fontawesomeerror](https://cloud.githubusercontent.com/assets/20392598/24451132/1a435f1a-146d-11e7-80e2-e7cf8393efb5.png)

## Actual behavior:
CSS file: px-timeline-styles.html has path to font-awesome icons as ../font-awesome/fonts/fontawesome-webfont.eot?v=4.4.0

## Expected behavior :
which should be replaced with ../../font-awesome/fonts/fontawesome-webfont.eot?v=4.4.0 ,as px-timeline doesn't have any font-awesome folder of it's own.

Could you please look into this?

**Comment by randyaskin** [comment]
Both `polymer serve` and `gulp serve` are both able to resolve the path fine. This particular path comes from px-iconography-design, which is required by px-buttons-design, and is therefore used in pretty much *every* px- component. I see you've also been involved in [the other conversation on this topic](https://github.com/PredixDev/px-data-table/issues/93) over on data-table.

**Comment by randyaskin** [comment]
I believe Martin fixed this since the data-table issue is closed now.
