### ISSUE TITLE
Component does not support IE(Edge)

### ISSUE THREAD

**Issue by snehadr23** [predixdesignsystem/px-timeline#3]
Hi,

The component's text content is horizontally compressed in IE(please refer the screenshot). 

1. The text in the body occupies 100px - 150px width when it has about 500px available to it. 
2. The title of the node and the date overlap in IE instead of one below the other. 

These CSS issues make the text virtually unreadable on IE.
<img width="2039" alt="ie-11 px-timeline" src="https://cloud.githubusercontent.com/assets/25832968/25108385/4f461474-238a-11e7-897f-f205ec551142.png">

**Comment by randyaskin** [comment]
Fixed display issues for IE, Edge, and Safari in v0.2.0.
