### ISSUE TITLE
The date for the nodes and the node icons can be more customizable.

### ISSUE THREAD

**Issue by snehadr23** [predixdesignsystem/px-timeline#4]
Hi,

1. When the user doesn't need the time groups, there is no way to show the year in the date format for each node. There is no way for the user to know whether the data is from this year, last year or the year before because it currently shows just the month and date (boxed in the attached screenshot)

2. In the enhanced version of the component, when there is body text to be shown, i.e there is no node content to open and see, the node circle icon is different and smaller when compared to the icon for the node that has body content text for the user to open and see (circled in the attached screenshot).

<img width="801" alt="date and icon issue_px-timeline" src="https://cloud.githubusercontent.com/assets/25832968/25108772/14be2ce4-238d-11e7-81b3-1e35aa1d0c01.png">

**Comment by randyaskin** [comment]
Fixed display issue and added dateFormat property in v0.2.0.
