### ISSUE TITLE
px-timeline Time Zone Conversion 

### ISSUE THREAD

**Issue by AdmiralsGE** [predixdesignsystem/px-timeline#6]
1)	Application time changed in preferences will change entire application but the px-timeline is not able parse FIJI timezone. 
2)	Other than FIJI it works fine displaying time zone
![time zone fiji not displaying in timeline component](https://user-images.githubusercontent.com/32395033/31022958-6a6066ce-a508-11e7-877f-fbdf2331b59a.jpg)

![time zone working in application](https://user-images.githubusercontent.com/32395033/31023034-9d1aea94-a508-11e7-8ff5-eb38373498b5.jpg)

**Comment by randyaskin** [comment]
I'm not sure how your application is passing timezone data to your components, but the timeline has a property called `timeZone` and moment.js contains the timezone `Pacific/Fiji`, so you should either use `<px-timeline time-zone='Pacific/Fiji'>` or get a reference to the timeline component and set it with JavaScript, e.g. `myTimeline.set('timeZone', 'Pacific/Fiji');` - hope that helps!

**Comment by AdmiralsGE** [comment]
Thank You Randy, 
We need to change based on the time pref. per our application USER PREF. Fiji is one the time zone we are trying to test it, per below screenshot we are passing time zone to this <px-timeline time-zone='Pacific/Fiji'> component but its not able to parse it.

![px timeline error](https://user-images.githubusercontent.com/32395033/31029121-839c22de-a51e-11e7-8751-6c4265e44e7f.png)

**Comment by randyaskin** [comment]
I'm not following. It seems to be parsing it fine, and +12 is the correct timezone for Fiji. I tested on our demo page by switching from my local time zone (-8) to Fiji (+12) and it only jumped forward by 19 hours, so I'm not sure if there's a daylight savings difference or something? 

By "not parsing" do you mean the time in the timeline is different than the one in your case details? I find it odd that the difference is not just the timezone - it's not off by an even hour, the minutes and seconds are different as well.

**Comment by AdmiralsGE** [comment]
Thanks for quick response,  Instead of +12 we wanted to see FJT timezone,  like we can see GMT or EDT when changed in time preferences.

**Comment by randyaskin** [comment]
That is a limitation of the moment timezone library, not of this component. I tried `z`, `zz`, `Z`, and `ZZ`, none of them translate to "FJT" unfortunately.
